name: Deploy to AWS S3
on:
  push:
    branches: [main]
  repository_dispatch:
    types: [trigger-build]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ENV_AWS_LAMBDA_FUNCTION_NAME: ${{ secrets.ENV_AWS_LAMBDA_FUNCTION_NAME }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 sync ./_next s3://${{ secrets.ENV_AWS_S3_BUCKET_NAME }} --cache-control immutable,max-age=31536000,public
      - run: aws s3 sync ./out s3://${{ secrets.ENV_AWS_S3_BUCKET_NAME }} --cache-control must-revalidate,max-age=0,public
