name: Deploy to AWS S3
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
        env:
          ENV_AWS_ACCESS_KEY_ID: ${{ secrets.ENV_AWS_ACCESS_KEY_ID }}
          ENV_AWS_SECRET_ACCESS_KEY: ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
          ENV_AWS_DEFAULT_REGION: ${{ secrets.ENV_AWS_DEFAULT_REGION }}
          ENV_AWS_LAMBDA_FUNCTION_NAME: ${{ secrets.ENV_AWS_LAMBDA_FUNCTION_NAME }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ENV_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ENV_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.ENV_AWS_DEFAULT_REGION }}
      - run: aws s3 sync ./out s3://${{ secrets.ENV_AWS_S3_BUCKET_NAME }}
